### PR TITLE
restart:always on all containers

### LINKED ISSUE #192: Ensure automatic ARTEMIS recovery upon physical server reboot
**Is your feature request related to a problem? Please describe.**
When the server running ARTEMIS is reboot, ARTEMIS should properly recover at its previous stage (maybe by defaulting to monitor, detect and mitigate services to "OFF" as normal, but in any case being able to run without any issues).

**Describe the solution you'd like**
Automatic recovery without the user needing to restart docker-compose.

**Describe alternatives you've considered**
N/A

**Additional context**
https://forums.docker.com/t/how-to-handle-server-reboot-when-using-docker-compose/26374

Connected with #231 (regarding module reset).

### PR DESCRIPTION
**Pull request by vkotronis**
### Description of PR

What component(s) does this PR affect?

- [ ] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [X] Build System

Does the PR require changes on other components? If yes, please mark the components:

- [ ] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

### Related Issue

Resolves #192

### Solution

Always restart composed containers (dependencies are already handled correctly)

### Type

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] None of the above

### Checklist:

- [X] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by slowr** [comment]
:running: **Benchmark Results** :running:
- BGP Updates (updates/sec): **695**
- Hijacks Detected (hijacks/sec): **25**

**Comment by vkotronis** [comment]
I get:
```
ckend           | nc: bad address 'rabbitmq'
frontend          | nc: bad address 'rabbitmq'
backend           | nc: bad address 'rabbitmq'
frontend          | nc: bad address 'rabbitmq'
backend           | nc: bad address 'rabbitmq'
frontend          | nc: bad address 'rabbitmq'
backend           | nc: bad address 'rabbitmq'
frontend          | nc: bad address 'rabbitmq'
postgrest         | {"details":"could not translate host name \"postgres\" to address: Name or service not known\n","code":"","message":"Database connection error"}
postgrest         | Attempting to reconnect to the database in 32 seconds...
backend           | nc: bad address 'rabbitmq'
frontend          | nc: bad address 'rabbitmq'
backend           | nc: bad address 'rabbitmq'
frontend          | nc: bad address 'rabbitmq'
backend           | nc: bad address 'rabbitmq'
frontend          | nc: bad address 'rabbitmq'
backend           | nc: bad address 'rabbitmq'
```
even with this fix after reboot

**Comment by vkotronis** [comment]
Sometimes containers may get stuck at the following state:
```
artemis_admin@artemis:~/artemis$ docker-compose ps
     Name                   Command                 State       Ports  
-----------------------------------------------------------------------
backend          ./entrypoint                     Up           9001/tcp
frontend         ./entrypoint                     Up           8000/tcp
graphql          graphql-engine serve             Restarting           
monitor          ./entrypoint                     Up           9001/tcp
nginx            nginx -g daemon off;             Exit 127             
pg-amqp-bridge   /root/wait-for rabbitmq:56 ...   Exit 127             
postgres         ./postgres-entrypoint.sh         Exit 127             
postgrest        /bin/sh -c exec postgrest  ...   Up           3000/tcp
rabbitmq         docker-entrypoint.sh rabbi ...   Exit 127  
```

No idea why this might happen upon restart of server (tried on VM). It does not happen consistently too; sometimes everything works fine...

**Comment by vkotronis** [comment]
Will merge after finding out what is this `Exit 127` error about (seems related to docker, not ARTEMIS).

**Comment by vkotronis** [comment]
@slowr any ideas on the `Exit 127` error? Seems to be related to some docker issue, rather than ARTEMIS...

**Comment by vkotronis** [comment]
Merging and closing, since it seems to work in production

**Pull request merged**
