### PR TITLE
bgpstreamkafka client/tap

### LINKED ISSUE #280: Add private beta BMP feed to ARTEMIS
**Is your feature request related to a problem? Please describe.**
Missing documentation on how a developer can add a custom taps (e.g., private BMP feed).

**Describe the solution you'd like**
[Wiki page for private BMP feeds](https://github.com/FORTH-ICS-INSPIRE/artemis/wiki/Private-BMP-feeds-using-bgpstreamlive)

[WIki page for devs only](https://github.com/FORTH-ICS-INSPIRE/artemis/wiki/(Dev-only)-Adding-a-custom-tap-to-ARTEMIS)

### PR DESCRIPTION
**Pull request by vkotronis**
### Description of PR

What component(s) does this PR affect?

- [X] Back-End (Database, Detection/Configuration/etc. Microservices)
- [ ] Front-End (Flask, API, UI, etc)
- [ ] Monitor (RIPE RIS, BGPStream RV/RIS/CAIDA, etc.)
- [X] Docs (incl. wiki)
- [ ] Build System

Does the PR require changes on other components? If yes, please mark the components:

- [ ] Back-End (Database, Detection/Configuration/etc. Microservices)
- [ ] Front-End (Flask, API, UI, etc)
- [ ] Monitor (RIPE RIS, BGPStream RV/RIS/CAIDA, etc.)
- [ ] Docs (incl. wiki)
- [ ] Build System

### Related Issue

Resolves #280

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] None of the above

### Checklist:

- [X] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [x] This change requires a change in the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by slowr** [comment]
:running: **Benchmark Results** :running:
- BGP Updates (updates/sec): **672**
- Hijacks Detected (hijacks/sec): **26**

**Comment by vkotronis** [comment]
TODO: testing!!!

**Comment by vkotronis** [comment]
Currently for testing:
```
  bgpstreamkafka:
    host: bmp.bgpstream.caida.org
    port: 9092
    topic: "^openbmp\\.router--.+\\.peer-as--.+\\.bmp_raw"
```

**Comment by slowr** [comment]
:running: **Benchmark Results** :running:
- BGP Updates (updates/sec): **701**
- Hijacks Detected (hijacks/sec): ****

**Comment by vkotronis** [comment]
Connected to https://github.com/slowr/bgpstream-redis/pull/3 as the latest image

**Comment by alistairking** [comment]
You might not need to escape the backslashes like that.
My guess is that this is what you want:
```
  bgpstreamkafka:
    host: bmp.bgpstream.caida.org
    port: 9092
    topic: "^openbmp\.router--.+\.peer-as--.+\.bmp_raw"
```

**Comment by slowr** [comment]
:running: **Benchmark Results** :running:
- BGP Updates (updates/sec): **682**
- Hijacks Detected (hijacks/sec): **25**

**Comment by slowr** [comment]
:running: **Benchmark Results** :running:
- BGP Updates (updates/sec): **678**
- Hijacks Detected (hijacks/sec): **27**

**Comment by vkotronis** [comment]
> You might not need to escape the backslashes like that.
> My guess is that this is what you want:
> 
> ```
>   bgpstreamkafka:
>     host: bmp.bgpstream.caida.org
>     port: 9092
>     topic: "^openbmp\.router--.+\.peer-as--.+\.bmp_raw"
> ```

Done, works ok. We simply need to resolve the issue with the Python version in the bgpstream container and we are all set.

**Comment by vkotronis** [comment]
Merging since no further comments

**Pull request merged**
