### PR TITLE
update codemirror version

### PR DESCRIPTION
**Pull request by pgigis**
### Description of PR
Update codemirror version from 5.42.0 to the latest (5.53.2)

What component(s) does this PR affect?

- [ ] Back-End (Database, Detection/Configuration/etc. Microservices)
- [X] Front-End (Flask, API, UI, etc)
- [ ] Monitor (RIPE RIS, BGPStream RV/RIS/CAIDA, etc.)
- [ ] Docs (incl. wiki)
- [ ] Build System

Does the PR require changes on other components? If yes, please mark the components:

- [ ] Back-End (Database, Detection/Configuration/etc. Microservices)
- [ ] Front-End (Flask, API, UI, etc)
- [ ] Monitor (RIPE RIS, BGPStream RV/RIS/CAIDA, etc.)
- [ ] Docs (incl. wiki)
- [ ] Build System

### Related Issue

Resolves #

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] None of the above

### Checklist:

- [ ] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pgigis** [comment]
Don't merge yet. Needs more testing

**Comment by pgigis** [comment]
Should we merge this?

**Comment by vkotronis** [comment]
Closing this as identical to https://github.com/FORTH-ICS-INSPIRE/artemis/pull/367 (work is moved there)

**Comment by slowr** [comment]
Closing the PR for now as upgrading CM does not solve the issue we had

**Pull request closed without merging**
