### PR TITLE
Migrating from travis to GH actions

### LINKED ISSUE #568: Migrate from travis to GitHub actions
**Is your feature request related to a problem? Please describe.**
While travis has served this open-source project perfectly during the last year, the new status where they move away from
open-source has started severely affecting our CI/CD pipelines.

**Describe the solution you'd like**
Use GitHub actions instead of travis.

**Describe alternatives you've considered**
N/A. GitHub actions seems to be the option of choice (state-of-the-art), and does not require third-party integrations.

**Additional context**
https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions
https://deanattali.com/blog/migrating-travis-to-github/

### PR DESCRIPTION
**Pull request by vkotronis**
### Description of PR

What component(s) does this PR affect?

- [ ] Back-End (Database, Detection/Configuration/etc. Microservices)
- [ ] Front-End (Flask, API, UI, etc)
- [ ] Monitor (RIPE RIS, BGPStream RV/RIS/CAIDA, etc.)
- [ ] Docs
- [X] Build System

Does the PR require changes on other components? If yes, please mark the components:

- [ ] Back-End (Database, Detection/Configuration/etc. Microservices)
- [ ] Front-End (Flask, API, UI, etc)
- [ ] Monitor (RIPE RIS, BGPStream RV/RIS/CAIDA, etc.)
- [ ] Docs
- [ ] Build System

### Related Issue

Resolves #568 

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [X] None of the above

### Checklist:

- [X] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by vkotronis** [comment]
TODO:
[ ] https://github.com/FORTH-ICS-INSPIRE/artemis/actions/runs/618061127 `the input device is not a TTY` while docker run
[ ] Re-check and test benchmark

**Comment by vkotronis** [comment]
@slowr one remaining issue is that the benchmark does not report back results because of:
```
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```
The command I am using is:
```
docker run --rm --env-file .env -e "REPO_SLUG=$GITHUB_REPOSITORY" -e "GITHUB_TOKEN=$GITHUB_TOKEN" -e "PULL_REQUEST_NUMBER=$TRAVIS_PULL_REQUEST"  --network artemis_artemis artemis_benchmark
```
Can it be that the token var is not correct?

**Review by slowr — APPROVED** [review]
LGTM! Very good work!
Have to tested it maybe with an external fork?

**Comment by vkotronis** [comment]
> LGTM! Very good work!
> Have to tested it maybe with an external fork?

You are right I will test it on one fork of mine to make sure that the correct things happen. Will update here.

**Comment by vkotronis** [comment]
> > LGTM! Very good work!
> > Have to tested it maybe with an external fork?
> 
> You are right I will test it on one fork of mine to make sure that the correct things happen. Will update here.

There is a small bug on GH actions when you use the same branch to test from a fork, so I will merge this for now and we see if we encounter any pull problems from forks in the future. There is no danger on that front since only local PRs may actually push images.

**Pull request merged**
