### PR TITLE
Ensure ARTEMIS config file is not clobbered on pod restart

### PR DESCRIPTION
**Pull request by alistairking**
### Description of PR

Previously when the backend pod restarted it would overwrite the config file in persistent storage with the one from the configmap (i.e., the default). The `-u` option to `cp` doesn't seem to be enough to prevent an overwrite (presumably the modification time of the file from the configmap cannot be trusted). Using both `-u` and the `-n` (no-clobber) option seems to work and prevent the persisted config file from being overwritten.

What component(s) does this PR affect?

- [ ] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [X] Build System

Does the PR require changes on other components? If yes, please mark the components:

- [ ] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

### Related Issue

Resolves #

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] None of the above

### Checklist:

- [X] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alistairking** [comment]
@slowr which file(s) do you want to change behavior for in the monitor deployment template? i wasn't aware that the system can modify files other than the config.

**Comment by slowr** [comment]
@alistairking not yet but we might make `logging.yaml` modifiable as well to add/remove loggers through GUI (for slack, etc)

**Comment by alistairking** [comment]
@slowr gotcha, ok so then how about i just add `-i` to all these `cp` commands so that all files installed in the PVC are not touched by pod restarts/upgrades

**Comment by alistairking** [comment]
@slowr done

**Pull request merged**
