### PR TITLE
Check messages for timestamps in future datetime. Fixes #469

### LINKED ISSUE #469: Routeviews EQUINIX introducing future date BGP updates
**Describe the bug**
From time to time I notice BGP updates from route-views.eqix with timestamp > now.

**Affected Component(s)**
- [X] Back-End - Monitor
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
1. For example add 1.1.1.0/24, 1.0.0.0/24 in config. It happens with other prefixes as well; those seem to have more frequent updates.
2. Once microservices are reloaded visit the Updates page and watch for the next updates for the above prefixes.
3. You will notice that there are updates that bear a timestamp in the future.
To make sure that this was not an Artemis issue, I installed pybgpstream and wrote a small script. It gets updates only from routeviews. For every message it parses the record timestamp and compares it to current timestamp (now - rec.time). This should always be >= 0. However in some cases negative results appeared, verifying it is not an Artemis issue but rather a pybgpstream/libbgpstream or even a route server glitch.
```
from _pybgpstream import BGPStream
import time
WATCHLIST = ['8.8.8.0/24', '1.1.1.0/24', '84.205.64.0/24', '1.1.0.0/24', '8.8.4.0/24', '64.6.64.0/24',
             '9.9.9.0/24', '1.0.0.0/24', '208.67.222.0/24', '139.91.250.0/24',
             '139.91.2.0/24', '2606:4700:4700::/48', '83.212.9.0/24', '23.129.128.0/24',
             '67.221.245.0/24', '84.205.80.0/24', '89.46.125.0/24', '192.5.6.0/24']

stream = BGPStream()

stream.add_filter("project", "routeviews")

for p in WATCHLIST:
    stream.add_filter("prefix", p)

stream.add_filter("record-type", "updates")

# Start 2 mins prior to now
start = int(time.time()) - 120
# live streaming
end = 0
stream.set_live_mode()

stream.add_interval_filter(start, end)
stream.start()

while True:
    try:
        rec = stream.get_next_record()
    except BaseException:
        continue
    if (rec.status != "valid") or (rec.type != "update"):
        continue

    # get next element
    try:
        elem = rec.get_next_elem()
    except BaseException:
        continue

    while elem:
        if elem.type in {"A", "W"}:
            this_prefix = str(elem.fields["prefix"])
            service = str(rec.collector)
            type_ = elem.type
            timestamp = float(rec.time)
            peer_asn = elem.peer_asn
            try:
                as_path = elem.fields["as-path"]
            except Exception as e:
                as_path = ''
            try:
                communities = elem.fields["communities"]
            except Exception as e:
                communities = set()
            now = time.time()

            diff = now - timestamp
            warn_text = '  '
            if diff < 0:
                # Flux capacitor charged... back to the future
                warn_text = '**'
            print(warn_text, this_prefix, service, type_, peer_asn,
                  communities, as_path, timestamp, now, diff)
        try:
            elem = rec.get_next_elem()
        except BaseException:
            continue
```
Here are some results:
```
   1.1.1.0/24 route-views.rio A 52720 set() 52720 267313 28598 13335 1603713594.929067 1603713659.6095612 64.68049430847168
   1.0.0.0/24 route-views.rio A 52720 set() 52720 267313 28598 13335 1603713594.929067 1603713659.6095982 64.68053126335144
** 1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603713752.983339 1603713673.4225802 -79.56075882911682
** 1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603713752.983339 1603713673.4226623 -79.56067681312561
** 1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603713873.003503 1603713673.4627683 -199.54073476791382
** 1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603713873.003503 1603713673.4628353 -199.5406677722931
** 1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714053.033151 1603713673.521544 -379.5116069316864
** 1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714053.033151 1603713673.5216155 -379.51153540611267
** 1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714143.051564 1603713674.382297 -468.6692669391632
** 1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714143.051564 1603713674.3823693 -468.66919469833374
** 89.46.125.0/24 route-views.eqix A 37468 {'37468:12000', '37468:2211', '37468:2000', '37468:12100', '37468:2200', '0:12833', '37468:2210', '8220:65030', '8220:65000', '37468:12101', '37468:37468', '8220:65403'} 37468 8220 51492 1603714300.47168 1603713674.4614234 -626.0102565288544
** 1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714353.092993 1603713674.4875982 -678.6053948402405
** 1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714353.092993 1603713674.4876633 -678.6053297519684
** 1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714383.098607 1603713674.5071042 -708.591502904892
** 1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714383.098607 1603713674.5071812 -708.5914258956909
** 1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714413.104765 1603713674.5264251 -738.5783398151398
** 1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714413.104765 1603713674.5264902 -738.5782747268677
** 89.46.125.0/24 route-views.eqix A 37468 {'37468:2241', '65101:1002', '65103:276', '37468:12000', '65102:1000', '37468:2000', '37468:2200', '37468:12400', '37468:2240', '37468:37468', '37468:12401', '65104:150'} 37468 51492 1603714499.197999 1603713674.554963 -824.6430358886719
...
...
   1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714533.122066 1603714541.870146 8.748080015182495
   1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714533.122066 1603714541.870238 8.748172044754028
** 1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714683.151157 1603714541.9569423 -141.19421458244324
** 1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714683.151157 1603714541.9570143 -141.19414258003235
** 1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714773.167605 1603714542.5624025 -230.60520243644714
** 1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714773.167605 1603714542.5624828 -230.605122089386
** 1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714896.387772 1603714542.6121604 -353.7756116390228
** 1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603714896.387772 1603714542.6122274 -353.7755446434021
** 1.1.1.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603715046.533997 1603714542.6554632 -503.87853384017944
** 1.0.0.0/24 route-views.eqix A 41095 set() 41095 3356 13335 1603715046.533997 1603714542.6555326 -503.8784644603729
** 84.205.64.0/24 route-views.eqix A 2914 {'2914:1206', '2914:410', '2914:2203', '2914:3200'} 2914 15562 12654 1603715102.00453 1603714542.6749525 -559.3295774459839
** 84.205.64.0/24 route-views.eqix A 3257 {'3257:8157', '3257:50002', '3257:51100', '3257:51102', '3257:30118'} 3257 6453 50628 12654 1603715102.020728 1603714542.6750972 -559.3456308841705
** 84.205.64.0/24 route-views.eqix A 16552 {'6453:50', '16552:10500', '6453:2000', '16552:9090', '6453:2200', '16552:20840', '16552:40011', '6453:2202'} 16552 6453 50628 12654 1603715102.088507 1603714542.675184 -559.4133229255676
** 84.205.64.0/24 route-views.eqix A 6830 {'17152:0', '6830:17415', '6830:17000', '6830:35307'} 6830 1299 50304 12654 1603715102.14148 1603714542.6752708 -559.4662091732025
** 84.205.64.0/24 route-views.eqix A 37468 {'37468:14000', '37468:1000', '37468:14100', '1299:30000', '37468:1412', '37468:1400', '37468:1002', '37468:37468', '37468:14101'} 37468 1299 50304 12654 1603715102.166857 1603714542.6753547 -559.4915022850037
** 84.205.64.0/24 route-views.eqix A 8220 {'8220:1299', '1299:30000', '8220:64006', '8220:65001', '8220:65400', '8220:65257'} 8220 1299 50304 12654 1603715102.188319 1603714542.6754315 -559.5128874778748
** 84.205.64.0/24 route-views.eqix A 11039 {'6461:5997'} 11039 6461 50304 12654 1603715102.221027 1603714542.6755455 -559.5454814434052
** 84.205.64.0/24 route-views.eqix A 3257 {'3257:4000', '3257:51400', '3257:50002', '3257:8020', '3257:51403', '3257:50122'} 3257 6391 12654 1603715102.232101 1603714542.675612 -559.5564889907837
** 84.205.64.0/24 route-views.eqix A 16552 {'6453:50', '16552:10500', '6453:2000', '6453:2200', '16552:20840', '16552:40011', '6453:2202', '16552:9100'} 16552 6453 50628 12654 1603715102.343834 1603714542.6757567 -559.6680772304535
** 84.205.64.0/24 route-views.eqix A 6830 {'17152:0', '6830:17415', '6830:17000', '6830:35307'} 6830 1299 50628 12654 1603715102.350653 1603714542.675811 -559.6748418807983
** 84.205.64.0/24 route-views.eqix A 37468 {'37468:14000', '37468:1000', '37468:14100', '1299:30000', '37468:1412', '37468:1400', '37468:1002', '37468:37468', '37468:14101'} 37468 1299 50628 12654 1603715102.407459 1603714542.675914 -559.7315449714661
```
Looking at the time diff pattern, this looks like some sort of echo or retries. In any case, these messages should be ignored. 

**Expected behavior**
BGP update messages with future timestamp should be considered invalid.

**Proposed fix**
Another check should be added here: https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/utils/artemis_utils/__init__.py#L751
I managed to get rid of the future updates by patching the artemis_utils:
```
--- a/utils/artemis_utils/__init__.py
+++ b/utils/artemis_utils/__init__.py
@@ -749,6 +749,9 @@ class mformat_validator:
             self.msg["timestamp"]
         ) < datetime.utcnow() - timedelta(hours=1, minutes=30):
             return False
+        if datetime.utcfromtimestamp(self.msg["timestamp"]
+        ) > datetime.utcnow():
+            return False
         return True
```
As artemis_utils is fetched from pypi and to quickly test, I copied the utils folder on the patched container and pointed requirements.txt reference to artemis_utils to the local folder. I don't know if there would be a better way to test this.

**System (please complete the following information):**
I have tried on various systems with more or less the same config
 - OS: [Centos 7]
 - Browser [Firefox:81,Chrome:86]
 - Version [ARTEMIS v.'latest@c29bb6a']

**Additional context**
-

### PR DESCRIPTION
**Pull request by leopoul**
### Description of PR
Fixes issue #469 by considering messages with future timestamps as invalid

What component(s) does this PR affect?

- [ ] Back-End (Database, Detection/Configuration/etc. Microservices)
- [ ] Front-End (Flask, API, UI, etc)
- [X] Monitor (RIPE RIS, BGPStream RV/RIS/CAIDA, etc.)
- [ ] Docs (incl. wiki)
- [ ] Build System

Does the PR require changes on other components? If yes, please mark the components:

- [ ] Back-End (Database, Detection/Configuration/etc. Microservices)
- [ ] Front-End (Flask, API, UI, etc)
- [ ] Monitor (RIPE RIS, BGPStream RV/RIS/CAIDA, etc.)
- [ ] Docs (incl. wiki)
- [ ] Build System

### Related Issue

Resolves #469 

### Solution

Adds extra check for message timestamps by comparing current timestamp (now) with received message timestamp.

### Type

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] None of the above

### Checklist:

- [X] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation.
- [ ] I have updated the documentation accordingly.

### Remarks
I have tried running pre-commit hooks however I got an error for an invalid character in simple_flow.js file.
```
[leopoul@tatooine artemis]$ git commit -m "Check messages for timestamps in future datetime. Fixes #469"
Check configuration files................................................Failed
- hook id: value-verification
- exit code: 1

E....
======================================================================
ERROR: test_db_version (__main__.TestStringMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/artemis/other/verify_script.py", line 42, in test_db_version
    testcafe_version = get_match_from_file(TESTCAFE_FILE, r"Database v.([0-9]*)")
  File "/opt/artemis/other/verify_script.py", line 17, in get_match_from_file
    content = "".join(f.readlines())
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4264: ordinal not in range(128)

----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (errors=1)

Backend Unit Tests...................................(no files to check)Skipped
Apply black formatter....................................................Passed
Reorder python imports...................................................Passed
Check for added large files..............................................Passed
Check python ast.........................................................Passed
Check docstring is first.................................................Passed
Check for merge conflicts................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Fix End of Files.........................................................Passed
Flake8...................................................................Passed
Fix requirements.txt.................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
```
The error appears to happen with character × here: https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/testing/testcafe/tests/simple-flow.js#L67 between the two new lines. 
Please let me know if I am missing something wrt contributing guide.

### CODE REVIEW

**Comment by slowr** [comment]
Thanks for the PR @leopoul 

I am going to merge master on your branch to re-run the tests and recheck the coverage as we fixed coverage on forks! After that we should be good to go!

**Comment by vkotronis** [comment]
@slowr we also need to update the artemis-utils pypi package and adjust the version in the requirements before merging. This PR will be a part of the next release 1.7.0.

**Review by vkotronis — APPROVED** [review]
@slowr After merge, we should update Pypi to 1.0.5 https://pypi.org/project/artemis-utils/#history
(I can do this after merge).

**Comment by vkotronis** [comment]
@leopoul please also update your branch to be in sync with current master, and then we can merge.

**Comment by leopoul** [comment]
Done @vkotronis. I merged with master and pushed.

**Comment by vkotronis** [comment]
@leopoul I upgraded artemis-utils to 1.0.5 to include your change.

**Pull request merged**
