### PR TITLE
Moving utility functions to external python package (hosted in pypi)

### PR DESCRIPTION
**Pull request by slowr**
### Description of PR

As we are growing the amount of modules having to maintain different utility folders that do the same is a lot of a boilerplate code. For that reason we moved the utility functions on a different package called `artemis-utils` that is hosted on PyPI.

⚠️ This PR should be checked after #444 ⚠️

What component(s) does this PR affect?

- [x] Back-End (Database, Detection/Configuration/etc. Microservices)
- [ ] Front-End (Flask, API, UI, etc)
- [x] Monitor (RIPE RIS, BGPStream RV/RIS/CAIDA, etc.)
- [ ] Docs (incl. wiki)
- [x] Build System

Does the PR require changes on other components? If yes, please mark the components:

- [ ] Back-End (Database, Detection/Configuration/etc. Microservices)
- [ ] Front-End (Flask, API, UI, etc)
- [ ] Monitor (RIPE RIS, BGPStream RV/RIS/CAIDA, etc.)
- [ ] Docs (incl. wiki)
- [ ] Build System

### Related Issue

Resolves #

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] None of the above

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [x] This change requires a change in the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by vkotronis** [comment]
Will review after https://github.com/FORTH-ICS-INSPIRE/artemis/pull/444 is properly checked and merged.

**Review by vkotronis — COMMENTED** [review]
Looks good to me, however: should we pay attention to anything else in the utils package? 

Will it get everything from  the .env without problems (have you tried checking if an .env change is properly reflected in the changed modules)? 

Will the serialization for ujson still be registered properly?

**Comment by slowr** [comment]
> Looks good to me, however: should we pay attention to anything else in the utils package?
> 
> Will it get everything from the .env without problems (have you tried checking if an .env change is properly reflected in the changed modules)?
> 
> Will the serialization for ujson still be registered properly?

The only thing that changes is that it uses an external package. The code is exactly the same and used the same way. The only problem that we could had was if we were using relative paths that were not it he package which is not the case.

For the future, we can add unit tests and make it compile with cython.

**Review by vkotronis — APPROVED** [review]
LGTM!

**Pull request merged**
