### PR TITLE
New table (dataplane_msms) and view (view_dataplane_msms) creation for hijack dataplane measurements (pings and traceroutes) #448

### LINKED ISSUE #448: New table (dataplane_msms) and view (view_dataplane_msms) creation for hijack dataplane measurements (pings and traceroutes)
I have create the new table named "dataplane_msms" in which we will save the results of the dataplane measurements (ping, traceroutes from RIPE Atlas) for a specific hijack detected by ARTEMIS. Furthermore, I have create a new view named "view_dataplane_msms" which help us to query the measurement results from the "dataplane_msms" in a safe manner for each hijack and display these to the frontend (with the help of the Graphql API).

### PR DESCRIPTION
**Pull request by georgeepta**
### Description of PR
#448  I have create the new table named "dataplane_msms" in which we will save the results of the dataplane measurements (ping, traceroutes from RIPE Atlas) for a specific hijack detected by ARTEMIS. Furthermore, I have create a new view named "view_dataplane_msms" which help us to query the measurement results from the "dataplane_msms" in a safe manner for each hijack and display these to the frontend (with the help of the Graphql API)        

What component(s) does this PR affect?

- [X] Back-End (Database, Detection/Configuration/etc. Microservices)
- [ ] Front-End (Flask, API, UI, etc)
- [ ] Monitor (RIPE RIS, BGPStream RV/RIS/CAIDA, etc.)
- [ ] Docs (incl. wiki)
- [ ] Build System

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] None of the above

Resolves #448 

### Checklist:

- [X] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by vkotronis** [comment]
Blocked by https://github.com/FORTH-ICS-INSPIRE/artemis/issues/450

Need to rerun CI tests after that issue is dealt with.

**Comment by vkotronis** [comment]
https://github.com/FORTH-ICS-INSPIRE/artemis/issues/450 is closed so now we can focus on this pull request.

**Review by vkotronis — APPROVED** [review]
Looks good to me (simple addition to DB and correct migration process), tests are passing OK.
I will wait for @slowr 's feedback and then will merge to master.

**Review by slowr — APPROVED** [review]
LGTM 🎉

**Pull request merged**
