### PR TITLE
Backend Throughput Tests

### LINKED ISSUE #236: Benchmark for Detector
**Is your feature request related to a problem? Please describe.**
We would like to have a benchmark tool that calculates the BGP updates per second that Detector can handle when all of them are hijacks and when none of the are hijacks.

**Describe the solution you'd like**
Use the custom tap and log the outbound number of BGP updates and also log between the stages to have metrics along the way.

Times:
Send update, Unhandled update in DB, Handled update in DB, Hijack in DB

### PR DESCRIPTION
**Pull request by slowr**
### Description of PR

Introduce throughput tests to have a metric when doing changes on the modules speed.

What component(s) does this PR affect?

- [x] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [x] Build System

Does the PR require changes on other components? If yes, please mark the components:

- [ ] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

### Related Issue

Resolves #236

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] None of the above

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by slowr** [comment]
This can be moved on another container which will only do the benchmarking instead of having it as a tap in monitor module. Any opinion @vkotronis ?

**Comment by vkotronis** [comment]
> This can be moved on another container which will only do the benchmarking instead of having it as a tap in monitor module. Any opinion @vkotronis ?

@slowr yes please move to separate benchmarking container (can be activated by the devs when needed)

**Comment by vkotronis** [comment]
@slowr could you also integrate this test in semaphore? Or is it dangerous? E.g., if throughput falls below 10 updates/sec on the detector we need to do sth.

**Comment by slowr** [comment]
:tada: Benchmark Results :tada:
1399.489066691865 updates/sec
111.97621821001587 hijacks/sec

**Comment by slowr** [comment]
:tada: *Benchmark Results* :tada:
BGP updates inserted (updates/sec): *1213*
Hijacks detected/inserted (hijacks/sec): *82*

**Comment by slowr** [comment]
:tada: **Benchmark Results** :tada:
- BGP Updates (updates/sec): **1255**
Hijacks Detected (hijacks/sec): **85**

**Comment by slowr** [comment]
:tada: **Benchmark Results** :tada:
- BGP Updates (updates/sec): **1033**
Hijacks Detected (hijacks/sec): **70**

**Pull request merged**
